/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assingment;

import assingment.backend.model.LocalStorage;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author MSI
 */
public class Admin_gui extends javax.swing.JFrame {

    
    
    public Admin_gui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        HR = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        HRA2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        HRA4 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        HRA3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        HRA1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        HRA = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(64, 5, 64));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Sitka Banner", 1, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("C.I.S");
        jLabel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 122, 60));

        jLabel11.setFont(new java.awt.Font("Sitka Banner", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Colombo Institute Of Studies");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 40));

        jPanel3.setBackground(new java.awt.Color(102, 0, 102));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assingment/img/log.png"))); // NOI18N
        jLabel5.setText("  Logout");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, 230, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 660));

        HR.setBackground(new java.awt.Color(64, 5, 64));
        HR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HRMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HRMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HRMouseExited(evt);
            }
        });
        HR.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assingment/img/hr-manager.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
        });
        HR.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 208, 148));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assingment/log.png"))); // NOI18N
        jLabel6.setText("Logout");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        HR.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 654, 151, -1));

        jPanel1.add(HR, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 220, 180));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 51));
        jLabel1.setText("Admin Dashbord ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, -1, 64));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 51));
        jLabel3.setText("X");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 0, 20, 30));

        HRA2.setBackground(new java.awt.Color(64, 5, 64));
        HRA2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HRA2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HRA2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HRA2MouseExited(evt);
            }
        });
        HRA2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assingment/log.png"))); // NOI18N
        jLabel16.setText("Logout");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        HRA2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 654, 151, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assingment/img/new-employee-icon-5-removebg-preview (1) (1).png"))); // NOI18N
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        HRA2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 170, -1));

        jPanel1.add(HRA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 120, 230, 180));

        HRA4.setBackground(new java.awt.Color(64, 5, 64));
        HRA4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HRA4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HRA4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HRA4MouseExited(evt);
            }
        });
        HRA4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assingment/img/492214-200 (1).png"))); // NOI18N
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        HRA4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 162, 155));

        jLabel22.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assingment/log.png"))); // NOI18N
        jLabel22.setText("Logout");
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });
        HRA4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 654, 151, -1));

        jPanel1.add(HRA4, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 390, 220, 180));

        HRA3.setBackground(new java.awt.Color(64, 5, 64));
        HRA3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HRA3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HRA3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HRA3MouseExited(evt);
            }
        });
        HRA3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assingment/img/360_F_305757777_8zQDaRz3Y9tW8Jpd0jdC5NQoCQPgav5Z (1).png"))); // NOI18N
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        HRA3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 150, 155));

        jLabel19.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assingment/log.png"))); // NOI18N
        jLabel19.setText("Logout");
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        HRA3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 654, 151, -1));

        jPanel1.add(HRA3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, 220, 180));

        HRA1.setBackground(new java.awt.Color(64, 5, 64));
        HRA1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HRA1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HRA1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HRA1MouseExited(evt);
            }
        });
        HRA1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assingment/img/dpt.png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        HRA1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 20, 189, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assingment/log.png"))); // NOI18N
        jLabel13.setText("Logout");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        HRA1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 654, 151, -1));

        jPanel1.add(HRA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, -1, 180));

        HRA.setBackground(new java.awt.Color(64, 5, 64));
        HRA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HRAMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HRAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HRAMouseExited(evt);
            }
        });
        HRA.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assingment/img/hr-assitance.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        HRA.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 44, -1, 155));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assingment/log.png"))); // NOI18N
        jLabel10.setText("Logout");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        HRA.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 654, 151, -1));

        jPanel1.add(HRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, -1, 180));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 102));
        jLabel4.setText("Employee");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 290, 140, 50));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 0, 102));
        jLabel7.setText("Employee Search");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 570, 230, 40));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 0, 102));
        jLabel14.setText("HR Assistant");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 300, 140, 40));

        jLabel17.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 0, 102));
        jLabel17.setText("HR Manager");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 140, 40));

        jLabel20.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 0, 102));
        jLabel20.setText("Department");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 570, 140, 40));

        jLabel23.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 0, 102));
        jLabel23.setText("Designation");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 570, 140, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1206, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1206, 659));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked

        this.setVisible(false);
        HR_Manager_gui form = new HR_Manager_gui();
        form.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    private void HRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HRMouseClicked

        this.setVisible(false);
        HR_Manager_gui form = new HR_Manager_gui();
        form.setVisible(true);        
    }//GEN-LAST:event_HRMouseClicked

    private void HRMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HRMouseExited
       Color clr=new Color(51,0,51);
       HR.setBackground(clr);        

    }//GEN-LAST:event_HRMouseExited

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        this.setVisible(false);
        HR_Assistant_gui form = new HR_Assistant_gui();
        form.setVisible(true);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseClicked

    private void HRMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HRMouseEntered
        Color clr=new Color(102,0,102);
        HR.setBackground(clr);
    }//GEN-LAST:event_HRMouseEntered

    private void HRAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HRAMouseClicked
        this.setVisible(false);
        HR_Assistant_gui form = new HR_Assistant_gui();
        form.setVisible(true);
    }//GEN-LAST:event_HRAMouseClicked

    private void HRAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HRAMouseExited
         Color clr=new Color(51,0,51);
         HRA.setBackground(clr); 
    }//GEN-LAST:event_HRAMouseExited

    private void HRAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HRAMouseEntered
        Color clr=new Color(102,0,102);
        HRA.setBackground(clr);
        //add addfile=new add();
        //addfile.setVisible(true);
        //this.hide();
    }//GEN-LAST:event_HRAMouseEntered

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        LocalStorage storage = new LocalStorage();
        if("Admin".equals(storage.getData("actor"))){
            this.setVisible(false);
            Admin_gui adminForm = new Admin_gui();
            adminForm.setVisible(true);
        }else if("HR Manager".equals(storage.getData("actor"))){
            this.setVisible(false);
            HR_Manager_dashboard hrManagerDash = new HR_Manager_dashboard();
            hrManagerDash.setVisible(true);
        }
        
        System.out.print(storage.getData("actor"));
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        this.setVisible(false);
        Department_gui form = new Department_gui();
        form.setVisible(true);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MouseClicked

    private void HRA1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HRA1MouseClicked
       this.setVisible(false);
        Department_gui form = new Department_gui();
        form.setVisible(true);    }//GEN-LAST:event_HRA1MouseClicked

    private void HRA1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HRA1MouseEntered
        Color clr=new Color(102,0,102);
        HRA1.setBackground(clr);
    }//GEN-LAST:event_HRA1MouseEntered

    private void HRA1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HRA1MouseExited
         Color clr=new Color(51,0,51);
         HRA1.setBackground(clr); 
    }//GEN-LAST:event_HRA1MouseExited

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        this.setVisible(false);
        Employee_gui form = new Employee_gui();
        form.setVisible(true);
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel16MouseClicked

    private void HRA2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HRA2MouseClicked
         Color clr=new Color(51,0,51);
         HRA2.setBackground(clr); 
        this.setVisible(false);
        Employee_gui form = new Employee_gui();
        form.setVisible(true);
    }//GEN-LAST:event_HRA2MouseClicked

    private void HRA2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HRA2MouseEntered
          Color clr=new Color(102,0,102);
          HRA2.setBackground(clr);
    }//GEN-LAST:event_HRA2MouseEntered

    private void HRA2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HRA2MouseExited
         Color clr=new Color(51,0,51);
         HRA2.setBackground(clr); 
    }//GEN-LAST:event_HRA2MouseExited

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        this.setVisible(false);
        Designation_gui form = new Designation_gui();
        form.setVisible(true);
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel19MouseClicked

    private void HRA3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HRA3MouseClicked
          this.setVisible(false);
        Designation_gui form = new Designation_gui();
        form.setVisible(true);
    }//GEN-LAST:event_HRA3MouseClicked

    private void HRA3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HRA3MouseEntered
        Color clr=new Color(102,0,102);
        HRA3.setBackground(clr);
    }//GEN-LAST:event_HRA3MouseEntered

    private void HRA3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HRA3MouseExited
         Color clr=new Color(51,0,51);
         HRA3.setBackground(clr); 
    }//GEN-LAST:event_HRA3MouseExited

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        this.setVisible(false);
        Employee_search form = new Employee_search();
        form.setVisible(true);
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel22MouseClicked

    private void HRA4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HRA4MouseClicked
        this.setVisible(false);
        Employee_search form = new Employee_search();
        form.setVisible(true);
    }//GEN-LAST:event_HRA4MouseClicked

    private void HRA4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HRA4MouseEntered
        Color clr=new Color(102,0,102);
        HRA4.setBackground(clr);
    }//GEN-LAST:event_HRA4MouseEntered

    private void HRA4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HRA4MouseExited
         Color clr=new Color(51,0,51);
         HRA4.setBackground(clr); 
    }//GEN-LAST:event_HRA4MouseExited

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
    int dialogResult = JOptionPane.showConfirmDialog(null, "Are you sure you want to logout?", "Logout Confirmation", JOptionPane.YES_NO_OPTION);
    if (dialogResult == JOptionPane.YES_OPTION) {
             this.setVisible(false);
             Login form = new Login();
             form.setVisible(true);
        }
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        int dialogResult = JOptionPane.showConfirmDialog(null, "Are you sure you want to logout?", "Logout Confirmation", JOptionPane.YES_NO_OPTION);
        if (dialogResult == JOptionPane.YES_OPTION) {
            this.setVisible(false);
            Login form = new Login();
            form.setVisible(true);
        }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HR;
    private javax.swing.JPanel HRA;
    private javax.swing.JPanel HRA1;
    private javax.swing.JPanel HRA2;
    private javax.swing.JPanel HRA3;
    private javax.swing.JPanel HRA4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSlider jSlider1;
    // End of variables declaration//GEN-END:variables
}
