/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assingment;

import assingment.backend.model.Department;
import assingment.backend.model.Designation;
import assingment.backend.model.Employee;
import assingment.backend.services.Department_service;
import assingment.backend.services.Designation_service;
import assingment.backend.services.Employee_service;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.font.PDType0Font;
import assingment.backend.model.LocalStorage;
/**
 *
 * @author User
 */
public class Employee_search extends javax.swing.JFrame {
    private int  empid = -1;
    public Employee_search() {
        initComponents();
        load_designation();
        load_department();
        all_data_load();
    }

    private void load_designation() {
       Designation_service desi_service = new Designation_service();
       List<Designation> designations = desi_service.dataToCombo();
      
       
       for (Designation designation : designations) {
           int id = designation.getId() ;
           String name = designation.getName();
           
           comboDesignation.addItem(id+ " - "+name);
        }

    }

    private void load_department() {
       Department_service dpt_service = new Department_service();
       List<Department> dpts = dpt_service.dataToCombo();
      
       
       for (Department one_dpt : dpts) {
           int id = one_dpt.getId() ;
           String name = one_dpt.getName();
           
           comboDepartment.addItem(id+ " - "+name);
        }    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txtEpf = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        selectedEmp = new javax.swing.JLabel();
        comboDepartment = new javax.swing.JComboBox<>();
        comboDesignation = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEmp = new javax.swing.JTable();
        btnDownload = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblLogout = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 102));
        jLabel2.setText("Search Employees");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 25, 447, 50));

        jLabel29.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(51, 0, 51));
        jLabel29.setText("Name :");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 99, -1, -1));

        txtName.setBackground(new java.awt.Color(255, 255, 255));
        txtName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtName.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(209, 170, 227)));
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        jPanel2.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 127, 349, 40));

        jLabel30.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(51, 0, 51));
        jLabel30.setText("EPF NO :");
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 99, -1, -1));

        txtEpf.setBackground(new java.awt.Color(255, 255, 255));
        txtEpf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtEpf.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(209, 170, 227)));
        txtEpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEpfActionPerformed(evt);
            }
        });
        jPanel2.add(txtEpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 127, 384, 40));

        jLabel32.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(51, 0, 51));
        jLabel32.setText("Designation :");
        jPanel2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 188, -1, -1));

        selectedEmp.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        selectedEmp.setForeground(new java.awt.Color(51, 0, 51));
        jPanel2.add(selectedEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 750, 20));

        comboDepartment.setBackground(new java.awt.Color(255, 255, 255));
        comboDepartment.setForeground(new java.awt.Color(51, 0, 51));
        comboDepartment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Department" }));
        comboDepartment.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 51)));
        jPanel2.add(comboDepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 215, 386, 40));

        comboDesignation.setBackground(new java.awt.Color(255, 255, 255));
        comboDesignation.setForeground(new java.awt.Color(51, 0, 51));
        comboDesignation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Designation" }));
        comboDesignation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 51)));
        jPanel2.add(comboDesignation, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 216, 346, 40));

        tblEmp.setBackground(new java.awt.Color(51, 51, 51));
        tblEmp.setForeground(new java.awt.Color(255, 255, 255));
        tblEmp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "EPF NO", "NIC", "Designation", "Department", "Salary", "BOD", "Tel", "Experience", "Qualification", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblEmp.setGridColor(new java.awt.Color(153, 153, 153));
        tblEmp.setSelectionBackground(new java.awt.Color(102, 102, 102));
        tblEmp.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tblEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmpMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblEmp);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 387, 769, 335));

        btnDownload.setBackground(new java.awt.Color(0, 51, 51));
        btnDownload.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnDownload.setForeground(new java.awt.Color(255, 255, 255));
        btnDownload.setText("Download");
        btnDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownloadActionPerformed(evt);
            }
        });
        jPanel2.add(btnDownload, new org.netbeans.lib.awtextra.AbsoluteConstraints(587, 268, 120, 40));

        btnSearch.setBackground(new java.awt.Color(51, 0, 51));
        btnSearch.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel2.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(719, 268, 122, 40));

        jLabel14.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 0, 102));
        jLabel14.setText("X");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(847, 6, -1, 20));

        jLabel34.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(51, 0, 51));
        jLabel34.setText("Department :");
        jPanel2.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 189, -1, 20));

        btnClear.setBackground(new java.awt.Color(102, 0, 51));
        btnClear.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel2.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 268, 120, 40));

        jPanel3.setBackground(new java.awt.Color(64, 5, 64));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sitka Banner", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Colombo Institute Of Studies");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 180, 40));

        jLabel3.setFont(new java.awt.Font("Sitka Banner", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("C.I.S");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 120, 60));

        jPanel4.setBackground(new java.awt.Color(102, 0, 102));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });

        lblLogout.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblLogout.setForeground(new java.awt.Color(255, 255, 255));
        lblLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assingment/img/log.png"))); // NOI18N
        lblLogout.setText("  Logout");
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblLogout)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 680, 200, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 875, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1077, 742));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed

    }//GEN-LAST:event_txtNameActionPerformed

    private void txtEpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEpfActionPerformed

    private void tblEmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmpMouseClicked
        int selectedRowIndex = tblEmp.getSelectedRow();
        empid = selectedRowIndex;
        String name = (String) tblEmp.getValueAt(selectedRowIndex, 1);
        selectedEmp.setText("Your Select Employee : "+name);
    }//GEN-LAST:event_tblEmpMouseClicked

    private void btnDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownloadActionPerformed
        if (empid == -1) {
            JOptionPane.showMessageDialog(null, "Please select an employee.", "No Employee Selected", JOptionPane.WARNING_MESSAGE);
            System.out.println("Table Clear");
            return; 
        }

         
        int EmployeeId = (int) tblEmp.getValueAt(empid, 0);
        String name = (String) tblEmp.getValueAt(empid, 1);
        String epfNum = (String) tblEmp.getValueAt(empid, 2);
        String nic = (String) tblEmp.getValueAt(empid, 3);
        String designation = (String) tblEmp.getValueAt(empid, 4);
        String department = (String) tblEmp.getValueAt(empid, 5);
        String salary = (String) tblEmp.getValueAt(empid, 6);
        String bod = (String) tblEmp.getValueAt(empid, 7);
        String phoneNumber = (String) tblEmp.getValueAt(empid, 8);
        String experience = (String) tblEmp.getValueAt(empid, 9);
        String qualifications = (String) tblEmp.getValueAt(empid, 10);
        
         try {
            // Specify the path to the font file
            String rootPath = System.getProperty("user.dir");

            // Specify the relative path to the font file
            String fontFilePath = rootPath + File.separator + "src" + File.separator + "assingment" + File.separator
                    + "font" + File.separator + "arial.ttf";
            PDDocument document = new PDDocument();
            PDPage page = new PDPage();
            document.addPage(page);

            PDPageContentStream contentStream = new PDPageContentStream(document, page);

            // Load the font file
            File fontFile = new File(fontFilePath);
            PDType0Font font = PDType0Font.load(document, fontFile);

            contentStream.setFont(font, 12);
            float companyNameY = page.getMediaBox().getHeight() - 50; 
            float padding = 10;

            String companyName = "COLOMBO INSTITUTE OF STUDY";
            float companyNameWidth = font.getStringWidth(companyName) / 1000f * 12;
            float companyNameX = (page.getMediaBox().getWidth() - companyNameWidth) / 2;
            
            String reportTitle = "Employee Form"; 
            float reportTitleWidth = font.getStringWidth(reportTitle) / 1000f * 12;
            float reportTitleX = (page.getMediaBox().getWidth() - reportTitleWidth) / 2;
            
            contentStream.beginText();
            contentStream.newLineAtOffset(companyNameX, companyNameY);
            contentStream.showText(companyName);
            contentStream.endText();

            float reportTitleY = companyNameY - padding * 2;

            contentStream.beginText();
            contentStream.newLineAtOffset(reportTitleX, reportTitleY);
            contentStream.showText(reportTitle);
            contentStream.endText();

        
            // Add text to the page
            float padding_body = 20;
            contentStream.setFont(font, 10);
            contentStream.beginText();
            contentStream.newLineAtOffset(100, 700);
            contentStream.showText("Name: " + name);
            contentStream.newLineAtOffset(0, -padding_body);
            contentStream.showText("Employee Id: " + EmployeeId);
            contentStream.newLineAtOffset(0, -padding_body);
            contentStream.showText("EPF Number: " + epfNum);
            contentStream.newLineAtOffset(0, -padding_body);
            contentStream.showText("NIC: " + nic);
            contentStream.newLineAtOffset(0, -padding_body);
            contentStream.showText("Designation: " + designation);
            contentStream.newLineAtOffset(0, -padding_body);
            contentStream.showText("Department: " + department);
            contentStream.newLineAtOffset(0, -padding_body);
            contentStream.showText("Salary: " + salary);
            contentStream.newLineAtOffset(0, -padding_body);
            contentStream.showText("Date of Birth: " + bod);
            contentStream.newLineAtOffset(0, -padding_body);
            contentStream.showText("Phone Number: " + phoneNumber);
            contentStream.newLineAtOffset(0, -padding_body);
            contentStream.showText("Experience: " + experience);
            contentStream.newLineAtOffset(0, -padding_body);
            contentStream.showText("Qualifications: " + qualifications);
            contentStream.endText();

            contentStream.close();

            JFileChooser saveChooser = new JFileChooser();
            saveChooser.setDialogTitle("Save PDF File");
            saveChooser.setFileFilter(new FileNameExtensionFilter("PDF Files", "pdf"));

            String employeeName = (String) tblEmp.getValueAt(empid, 1);
            saveChooser.setSelectedFile(new File(employeeName + ".pdf"));

            int saveReturnValue = saveChooser.showSaveDialog(null);
            if (saveReturnValue == JFileChooser.APPROVE_OPTION) {
                File saveFile = saveChooser.getSelectedFile();

                try {
                    empid = -1;
                    document.save(saveFile);
                    document.close();
                    int option = JOptionPane.showConfirmDialog(null, "PDF saved successfully. Do you want to open it?", "Open PDF", JOptionPane.YES_NO_OPTION);
                    if (option == JOptionPane.YES_OPTION) {
                        Desktop.getDesktop().open(saveFile);
                    }                
                } catch (IOException e) {
                    System.err.println("Error saving PDF: " + e.getMessage());
                    JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);

                }
            } else {
                System.out.println("No file selected for saving.");
                JOptionPane.showMessageDialog(null, "No file selected for saving.", "Information", JOptionPane.INFORMATION_MESSAGE);

            }

        } catch (IOException e) {
            System.err.println("Error creating PDF: " + e.getMessage());
            JOptionPane.showMessageDialog(null, "Error creating PDF: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);

        }
        
    }//GEN-LAST:event_btnDownloadActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
                
        String emname_txt = txtName.getText().isEmpty() ? "null" : txtName.getText();
        String emefp_txt = txtEpf.getText().isEmpty() ? "null" : txtEpf.getText();
        String designation = comboDesignation.getSelectedItem() == "Select Designation" ? "null" : (String) comboDesignation.getSelectedItem();
        String department = comboDepartment.getSelectedItem() == "Select Department" ? "null"  : (String) comboDepartment.getSelectedItem();
        
        Employee employee = new Employee();
        employee.searchFun(emname_txt , emefp_txt , designation , department);

        Employee_service emp_service = new Employee_service();
        List<Employee> emp_list;
        
        if (emname_txt.equals("null") && emefp_txt.equals("null") && designation.equals("null") && department.equals("null")) {
            emp_list = emp_service.retrieveAllEMP();
            JOptionPane.showMessageDialog(null, "All data are loaded", "Information", JOptionPane.INFORMATION_MESSAGE);
        }else{
            emp_list = emp_service.searchEMP(emname_txt, emefp_txt, department, designation);
        }
   
        if (emp_list.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No data found.", "Information", JOptionPane.INFORMATION_MESSAGE);
            String[] columnHeaders = new String[tblEmp.getColumnCount()];
            for (int i = 0; i < tblEmp.getColumnCount(); i++) {
                columnHeaders[i] = tblEmp.getColumnName(i);
            }
            DefaultTableModel newModel = new DefaultTableModel(columnHeaders, 0);
            tblEmp.setModel(newModel);
        } else {
            DefaultTableModel model = new DefaultTableModel();
                model.addColumn("ID");
                model.addColumn("Name");
                model.addColumn("EPF NO");
                model.addColumn("NIC");
                model.addColumn("Designation");
                model.addColumn("Department");
                model.addColumn("Salary");
                model.addColumn("Date of joining");
                model.addColumn("Tel");
                model.addColumn("Experience");
                model.addColumn("Qualification");

                for (Employee one_emp : emp_list) {
                    model.addRow(new Object[]{
                        one_emp.getId(),
                        one_emp.getName(),
                        one_emp.getEpf_num(),
                        one_emp.getNic(),
                        one_emp.getDesignation(),
                        one_emp.getDepartment(),
                        one_emp.getSalary(),
                        one_emp.getBod(),
                        one_emp.getPhoneNumber(),
                        one_emp.getExperience(),
                        one_emp.getQualifications()
                });
            }

            tblEmp.setModel(model);    
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked
        int option = JOptionPane.showConfirmDialog(this, "Are you sure you want to log out?", "Confirmation", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            this.setVisible(false);
            Login form = new Login();
            form.setVisible(true);
        }
    }//GEN-LAST:event_lblLogoutMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        LocalStorage storage = new LocalStorage();
        if("Admin".equals(storage.getData("actor"))){
            this.setVisible(false);
            Admin_gui adminForm = new Admin_gui();
            adminForm.setVisible(true);
        }else if("HR Manager".equals(storage.getData("actor"))){
            this.setVisible(false);
            HR_Manager_dashboard hrManagerDash = new HR_Manager_dashboard();
            hrManagerDash.setVisible(true);
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtName.setText("");
        txtEpf.setText("");
        comboDesignation.setSelectedItem("Select Designation");
        comboDepartment.setSelectedItem("Select Department");   
        DefaultTableModel model=(DefaultTableModel)tblEmp.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_btnClearActionPerformed

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        int dialogResult = JOptionPane.showConfirmDialog(null, "Are you sure you want to logout?", "Logout Confirmation", JOptionPane.YES_NO_OPTION);
        if (dialogResult == JOptionPane.YES_OPTION) {
            this.setVisible(false);
            Login form = new Login();
            form.setVisible(true);
        }
    }//GEN-LAST:event_jPanel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee_search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee_search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee_search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee_search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee_search().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDownload;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> comboDepartment;
    private javax.swing.JComboBox<String> comboDesignation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel selectedEmp;
    private javax.swing.JTable tblEmp;
    private javax.swing.JTextField txtEpf;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables

    private void all_data_load() {
         Employee_service emp_service = new Employee_service();
        List<Employee> emp_list = emp_service.retrieveAllEMP();
    
        DefaultTableModel model = new DefaultTableModel();
            model.addColumn("ID");
            model.addColumn("Name");
            model.addColumn("EPF NO");
            model.addColumn("NIC");
            model.addColumn("Designation");
            model.addColumn("Department");
            model.addColumn("Salary");
            model.addColumn("Date of joining");
            model.addColumn("Tel");
            model.addColumn("Experience");
            model.addColumn("Qualification");
            
            for (Employee one_emp : emp_list) {
                model.addRow(new Object[]{
                    one_emp.getId(),
                    one_emp.getName(),
                    one_emp.getEpf_num(),
                    one_emp.getNic(),
                    one_emp.getDesignation(),
                    one_emp.getDepartment(),
                    one_emp.getSalary(),
                    one_emp.getBod(),
                    one_emp.getPhoneNumber(),
                    one_emp.getExperience(),
                    one_emp.getQualifications()
            });
        }

        tblEmp.setModel(model);
    }

 
}
