/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assingment;

import assingment.backend.model.LocalStorage;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class HR_Manager_dashboard extends javax.swing.JFrame {

    /**
     * Creates new form HR_Manager_dashboard
     */
    public HR_Manager_dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        HR2 = new javax.swing.JPanel();
        lblEmployees = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        HR3 = new javax.swing.JPanel();
        lblEmpSearch = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        HR1 = new javax.swing.JPanel();
        lblDepartment = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        HRA2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        HRA3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lblDesignation = new javax.swing.JLabel();
        HRA4 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        HRA5 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(64, 5, 64));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Sitka Banner", 1, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("C.I.S");
        jLabel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 120, 60));

        jLabel10.setFont(new java.awt.Font("Sitka Banner", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Colombo Institute Of Studies");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 210, 40));

        jPanel3.setBackground(new java.awt.Color(102, 0, 102));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assingment/img/log.png"))); // NOI18N
        jLabel5.setText("  Logout");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 0, 140, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 220, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 677));

        HR2.setBackground(new java.awt.Color(64, 5, 64));
        HR2.setPreferredSize(new java.awt.Dimension(244, 710));
        HR2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HR2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HR2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HR2MouseExited(evt);
            }
        });
        HR2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEmployees.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblEmployees.setForeground(new java.awt.Color(255, 255, 255));
        lblEmployees.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assingment/img/new-employee-icon-5-removebg-preview (1) (1).png"))); // NOI18N
        lblEmployees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEmployeesMouseClicked(evt);
            }
        });
        HR2.add(lblEmployees, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 30, 171, 148));

        jLabel23.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assingment/log.png"))); // NOI18N
        jLabel23.setText("Logout");
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });
        HR2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 654, 151, -1));

        jPanel1.add(HR2, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 106, -1, 180));

        HR3.setBackground(new java.awt.Color(64, 5, 64));
        HR3.setPreferredSize(new java.awt.Dimension(244, 710));
        HR3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HR3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HR3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HR3MouseExited(evt);
            }
        });
        HR3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEmpSearch.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblEmpSearch.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assingment/img/jok.png"))); // NOI18N
        lblEmpSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEmpSearchMouseClicked(evt);
            }
        });
        HR3.add(lblEmpSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 134, 170));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assingment/log.png"))); // NOI18N
        jLabel12.setText("Logout");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        HR3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 654, 151, -1));

        jPanel1.add(HR3, new org.netbeans.lib.awtextra.AbsoluteConstraints(659, 391, -1, 180));

        HR1.setBackground(new java.awt.Color(64, 5, 64));
        HR1.setPreferredSize(new java.awt.Dimension(244, 710));
        HR1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HR1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HR1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HR1MouseExited(evt);
            }
        });
        HR1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDepartment.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDepartment.setForeground(new java.awt.Color(255, 255, 255));
        lblDepartment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assingment/img/dpt.png"))); // NOI18N
        lblDepartment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDepartmentMouseClicked(evt);
            }
        });
        HR1.add(lblDepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 31, 181, 148));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assingment/log.png"))); // NOI18N
        jLabel11.setText("Logout");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        HR1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 654, 151, -1));

        jPanel1.add(HR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(659, 106, -1, 180));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 51));
        jLabel1.setText("HR Manager Dashboard");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 15, -1, 64));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 51));
        jLabel3.setText("X");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(931, 6, 20, 30));

        HRA2.setBackground(new java.awt.Color(64, 5, 64));
        HRA2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HRA2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HRA2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HRA2MouseExited(evt);
            }
        });
        HRA2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assingment/log.png"))); // NOI18N
        jLabel14.setText("Logout");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        HRA2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 654, 151, -1));

        HRA3.setBackground(new java.awt.Color(64, 5, 64));
        HRA3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HRA3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HRA3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HRA3MouseExited(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assingment/img/hr-assitance.png"))); // NOI18N
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assingment/log.png"))); // NOI18N
        jLabel16.setText("Logout");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout HRA3Layout = new javax.swing.GroupLayout(HRA3);
        HRA3.setLayout(HRA3Layout);
        HRA3Layout.setHorizontalGroup(
            HRA3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HRA3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 189, Short.MAX_VALUE)
                .addGap(25, 25, 25))
            .addGroup(HRA3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(HRA3Layout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(35, Short.MAX_VALUE)))
        );
        HRA3Layout.setVerticalGroup(
            HRA3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HRA3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(HRA3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(HRA3Layout.createSequentialGroup()
                    .addGap(654, 654, 654)
                    .addComponent(jLabel16)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        HRA2.add(HRA3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 246, -1, 180));

        jLabel17.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 0, 102));
        jLabel17.setText("Department");
        HRA2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 436, 140, -1));

        lblDesignation.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDesignation.setForeground(new java.awt.Color(255, 255, 255));
        lblDesignation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assingment/img/360_F_305757777_8zQDaRz3Y9tW8Jpd0jdC5NQoCQPgav5Z (1) (1).png"))); // NOI18N
        lblDesignation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDesignationMouseClicked(evt);
            }
        });
        HRA2.add(lblDesignation, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 179, 166));

        HRA4.setBackground(new java.awt.Color(64, 5, 64));
        HRA4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HRA4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HRA4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HRA4MouseExited(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assingment/log.png"))); // NOI18N
        jLabel18.setText("Logout");
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });

        HRA5.setBackground(new java.awt.Color(64, 5, 64));
        HRA5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HRA5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HRA5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HRA5MouseExited(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assingment/img/hr-assitance.png"))); // NOI18N
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assingment/log.png"))); // NOI18N
        jLabel20.setText("Logout");
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout HRA5Layout = new javax.swing.GroupLayout(HRA5);
        HRA5.setLayout(HRA5Layout);
        HRA5Layout.setHorizontalGroup(
            HRA5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HRA5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 189, Short.MAX_VALUE)
                .addGap(25, 25, 25))
            .addGroup(HRA5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(HRA5Layout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(35, Short.MAX_VALUE)))
        );
        HRA5Layout.setVerticalGroup(
            HRA5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HRA5Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(HRA5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(HRA5Layout.createSequentialGroup()
                    .addGap(654, 654, 654)
                    .addComponent(jLabel20)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jLabel21.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 0, 102));
        jLabel21.setText("Department");

        jLabel22.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assingment/img/hr-assitance.png"))); // NOI18N
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout HRA4Layout = new javax.swing.GroupLayout(HRA4);
        HRA4.setLayout(HRA4Layout);
        HRA4Layout.setHorizontalGroup(
            HRA4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HRA4Layout.createSequentialGroup()
                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(HRA4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(HRA4Layout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(47, Short.MAX_VALUE)))
            .addGroup(HRA4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(HRA4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(HRA4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(HRA4Layout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(HRA5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        HRA4Layout.setVerticalGroup(
            HRA4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HRA4Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(HRA4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(HRA4Layout.createSequentialGroup()
                    .addGap(654, 654, 654)
                    .addComponent(jLabel18)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(HRA4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(HRA4Layout.createSequentialGroup()
                    .addGap(246, 246, 246)
                    .addComponent(HRA5, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addComponent(jLabel21)
                    .addContainerGap(246, Short.MAX_VALUE)))
        );

        HRA2.add(HRA4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 265, -1, 180));

        jPanel1.add(HRA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 391, -1, 180));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 102));
        jLabel4.setText("Designation");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 577, 140, -1));

        jLabel24.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(102, 0, 102));
        jLabel24.setText("Department");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(728, 298, 140, -1));

        jLabel25.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(102, 0, 102));
        jLabel25.setText("Employees");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 298, 140, -1));

        jLabel26.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(102, 0, 102));
        jLabel26.setText("Employee Letter");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(704, 577, 215, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(951, 677));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void HRA2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HRA2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_HRA2MouseExited

    private void HRA2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HRA2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_HRA2MouseEntered

    private void HRA2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HRA2MouseClicked
        this.setVisible(false);
        Designation_gui form = new Designation_gui();
        form.setVisible(true);
    }//GEN-LAST:event_HRA2MouseClicked

    private void lblDesignationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDesignationMouseClicked
        this.setVisible(false);
        Designation_gui form = new Designation_gui();
        form.setVisible(true);
    }//GEN-LAST:event_lblDesignationMouseClicked

    private void HRA3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HRA3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_HRA3MouseExited

    private void HRA3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HRA3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_HRA3MouseEntered

    private void HRA3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HRA3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_HRA3MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void HR1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HR1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_HR1MouseExited

    private void HR1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HR1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_HR1MouseEntered

    private void HR1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HR1MouseClicked
     this.setVisible(false);
        Department_gui form = new Department_gui();
        form.setVisible(true);
    }//GEN-LAST:event_HR1MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseClicked

    private void lblDepartmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDepartmentMouseClicked
        this.setVisible(false);
        Department_gui form = new Department_gui();
        form.setVisible(true);
    }//GEN-LAST:event_lblDepartmentMouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel20MouseClicked

    private void HRA5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HRA5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_HRA5MouseClicked

    private void HRA5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HRA5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_HRA5MouseEntered

    private void HRA5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HRA5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_HRA5MouseExited

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel22MouseClicked

    private void HRA4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HRA4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_HRA4MouseClicked

    private void HRA4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HRA4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_HRA4MouseEntered

    private void HRA4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HRA4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_HRA4MouseExited

    private void lblEmployeesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEmployeesMouseClicked
        this.setVisible(false);
        Employee_gui form = new Employee_gui();
        form.setVisible(true);
    }//GEN-LAST:event_lblEmployeesMouseClicked

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel23MouseClicked

    private void HR2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HR2MouseClicked
        this.setVisible(false);
        Employee_gui form = new Employee_gui();
        form.setVisible(true);    }//GEN-LAST:event_HR2MouseClicked

    private void HR2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HR2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_HR2MouseEntered

    private void HR2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HR2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_HR2MouseExited

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        LocalStorage storage = new LocalStorage();
        if("Admin".equals(storage.getData("actor"))){
            this.setVisible(false);
            Admin_gui adminForm = new Admin_gui();
            adminForm.setVisible(true);
        }else if("HR Manager".equals(storage.getData("actor"))){
            this.setVisible(false);
            HR_Manager_dashboard hrManagerDash = new HR_Manager_dashboard();
            hrManagerDash.setVisible(true);
        }        
    }//GEN-LAST:event_jLabel9MouseClicked

    private void lblEmpSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEmpSearchMouseClicked
        this.setVisible(false);
        Employee_search form = new Employee_search();
        form.setVisible(true);
    }//GEN-LAST:event_lblEmpSearchMouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseClicked

    private void HR3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HR3MouseClicked
        this.setVisible(false);
        Employee_search form = new Employee_search();
        form.setVisible(true);
    }//GEN-LAST:event_HR3MouseClicked

    private void HR3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HR3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_HR3MouseEntered

    private void HR3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HR3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_HR3MouseExited

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        int dialogResult = JOptionPane.showConfirmDialog(null, "Are you sure you want to logout?", "Logout Confirmation", JOptionPane.YES_NO_OPTION);
        if (dialogResult == JOptionPane.YES_OPTION) {
            this.setVisible(false);
            Login form = new Login();
            form.setVisible(true);
        }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        int dialogResult = JOptionPane.showConfirmDialog(null, "Are you sure you want to logout?", "Logout Confirmation", JOptionPane.YES_NO_OPTION);
        if (dialogResult == JOptionPane.YES_OPTION) {
            this.setVisible(false);
            Login form = new Login();
            form.setVisible(true);
        }
    }//GEN-LAST:event_jPanel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HR_Manager_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HR_Manager_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HR_Manager_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HR_Manager_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HR_Manager_dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HR1;
    private javax.swing.JPanel HR2;
    private javax.swing.JPanel HR3;
    private javax.swing.JPanel HRA2;
    private javax.swing.JPanel HRA3;
    private javax.swing.JPanel HRA4;
    private javax.swing.JPanel HRA5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblDepartment;
    private javax.swing.JLabel lblDesignation;
    private javax.swing.JLabel lblEmpSearch;
    private javax.swing.JLabel lblEmployees;
    // End of variables declaration//GEN-END:variables
}
