/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assingment;

import assingment.backend.model.HR_Manager;
import assingment.backend.model.LocalStorage;
import assingment.backend.model.User;
import assingment.backend.services.Hr_Manager_service;
import assingment.backend.services.User_service;
import assingment.backend.services.Validation_service;
import java.awt.Color;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MSI
 */
public class HR_Manager_gui extends javax.swing.JFrame {
    private String pass = "";
    private String email_for_delete = "";
    private int  id = 0;
    Validation_service validation = new Validation_service();

    
    public HR_Manager_gui() {
        initComponents();
        view_table();
        fun_desable_update_delete();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblLogout = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        txtNIC = new javax.swing.JTextField();
        txtBod = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        txtTel = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        txtEducationQualification = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        hrtable = new javax.swing.JTable();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(64, 5, 64));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Sitka Banner", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("C.I.S");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 120, 60));

        jLabel1.setFont(new java.awt.Font("Sitka Banner", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Colombo Institute Of Studies");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 180, 40));

        jPanel3.setBackground(new java.awt.Color(102, 0, 102));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });

        lblLogout.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblLogout.setForeground(new java.awt.Color(255, 255, 255));
        lblLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assingment/img/log.png"))); // NOI18N
        lblLogout.setText("  Logout");
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lblLogout)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblLogout))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 200, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 700));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 0, 102));
        jLabel14.setText("X");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 0, -1, 20));

        jLabel29.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(51, 0, 51));
        jLabel29.setText("Name :");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        txtName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtName.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(209, 170, 227)));
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 240, 40));

        jLabel30.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(51, 0, 51));
        jLabel30.setText("Address :");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, -1, -1));

        txtAddress.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtAddress.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(209, 170, 227)));
        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });
        jPanel1.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 240, 40));

        jLabel31.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(51, 0, 51));
        jLabel31.setText("NIC :");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, -1, -1));

        txtNIC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtNIC.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(209, 170, 227)));
        txtNIC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNICActionPerformed(evt);
            }
        });
        jPanel1.add(txtNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, 240, 40));

        txtBod.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtBod.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(209, 170, 227)));
        txtBod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBodActionPerformed(evt);
            }
        });
        jPanel1.add(txtBod, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 240, 40));

        jLabel32.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(51, 0, 51));
        jLabel32.setText("BOD :");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel33.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(51, 0, 51));
        jLabel33.setText("Email :");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, -1, -1));

        txtEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(209, 170, 227)));
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 240, 40));

        jLabel34.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(51, 0, 51));
        jLabel34.setText("Tel :");
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, -1, -1));

        txtTel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(209, 170, 227)));
        txtTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelActionPerformed(evt);
            }
        });
        jPanel1.add(txtTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 210, 240, 40));

        jLabel36.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(51, 0, 51));
        jLabel36.setText("Education Qualification");
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        txtEducationQualification.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtEducationQualification.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(209, 170, 227)));
        txtEducationQualification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEducationQualificationActionPerformed(evt);
            }
        });
        jPanel1.add(txtEducationQualification, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 790, 40));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 102));
        jLabel2.setText("HR Manager Registration Form");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 510, 90));

        btnSave.setBackground(new java.awt.Color(51, 0, 51));
        btnSave.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 370, 120, 40));

        btnDelete.setBackground(new java.awt.Color(204, 0, 0));
        btnDelete.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 370, 120, 40));

        btnUpdate.setBackground(new java.awt.Color(0, 51, 51));
        btnUpdate.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, 120, 40));

        hrtable.setBackground(new java.awt.Color(51, 51, 51));
        hrtable.setForeground(new java.awt.Color(255, 255, 255));
        hrtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "HR ID", "Title 2"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        hrtable.setGridColor(new java.awt.Color(153, 153, 153));
        hrtable.setSelectionBackground(new java.awt.Color(102, 102, 102));
        hrtable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        hrtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hrtableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(hrtable);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 800, 230));

        btnClear.setBackground(new java.awt.Color(102, 0, 0));
        btnClear.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, 120, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 840, 690));

        setSize(new java.awt.Dimension(1038, 689));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked
        int option = JOptionPane.showConfirmDialog(this, "Are you sure you want to log out?", "Confirmation", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            this.setVisible(false);
            Login form = new Login();
            form.setVisible(true);
        }
    }//GEN-LAST:event_lblLogoutMouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed

    }//GEN-LAST:event_txtNameActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void txtNICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNICActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNICActionPerformed

    private void txtBodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBodActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelActionPerformed

    private void txtEducationQualificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEducationQualificationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEducationQualificationActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
 
        User_service user_service = new User_service();
        String name_txt = txtName.getText();
        String add_txt = txtAddress.getText();
        String nic_txt = txtNIC.getText();
        String dob_txt = txtBod.getText();
        String email_txt = txtEmail.getText();
        String passs = user_service.password_generate();
        String eq_txt = txtEducationQualification.getText();
        String tel = txtTel.getText();
        
        boolean isValid = true;
        StringBuilder errorMessage = new StringBuilder();
        
        if (!validation.isValidNIC(nic_txt)) {
            isValid = false;
            errorMessage.append("Please enter a valid NIC number.\n");
        }
        
        if (!validation.isValidEmail(email_txt)) {
            isValid = false;
            errorMessage.append("Please enter a valid email address.\n");
        }
        
        if (!validation.isValidPhoneNumber(tel)) {
            isValid = false;
            errorMessage.append("Please enter a valid telephone number.\n");
        }
        
       
        
        if (add_txt.isEmpty() || nic_txt.isEmpty() || dob_txt.isEmpty() || email_txt.isEmpty() || eq_txt.isEmpty()) {
            isValid = false;
            errorMessage.append("Please fill in all required fields.\n");
        }
        
        if (!isValid) {
            JOptionPane.showMessageDialog(this, errorMessage.toString(), "Error", JOptionPane.WARNING_MESSAGE);
        }else{
        
            HR_Manager hr = new HR_Manager (name_txt , add_txt , nic_txt , dob_txt , eq_txt , 0 , email_txt , passs , "HR Manager" , tel, "2014-02-10");
            Hr_Manager_service hr_service = new Hr_Manager_service();
            boolean save_status = hr_service.createUser(hr);
            if (save_status) {
                fun_desable_update_delete();
                JOptionPane.showMessageDialog(null, "HR Manager is saved. Passowrd Is : "+passs, "Save Successful", JOptionPane.INFORMATION_MESSAGE);
                clearfun();
                view_table();
                
                 User_service usr_service = new User_service();
                 usr_service.download_password(passs , email_txt);
            }else{
                JOptionPane.showMessageDialog(null, "Data saving failed.", "Save Failed", JOptionPane.ERROR_MESSAGE);

            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int choice = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete?", "Confirmation", JOptionPane.YES_NO_OPTION);

        if (choice == JOptionPane.YES_OPTION) {

            HR_Manager hrm = new HR_Manager();
            hrm.setId(id);

            Hr_Manager_service hr_m_service = new Hr_Manager_service();
            boolean delete_status = hr_m_service.deleteUser(id , email_for_delete);
            if (delete_status) {
                view_table();
                fun_desable_update_delete();
                clearfun();
                JOptionPane.showMessageDialog(null, "HR Manager deleted successfully", "Delete Status", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Failed to delete HR Manager", "Delete Status", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Cancel deleting.", "Cancel Delete", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        int choice = JOptionPane.showConfirmDialog(null, "Are you sure you want to update?", "Confirmation", JOptionPane.YES_NO_OPTION);

        if (choice == JOptionPane.YES_OPTION) {
            String name_txt = txtName.getText();
            String add_txt = txtAddress.getText();
            String eq_txt = txtEducationQualification.getText();
            String passv= pass;



            if (add_txt.isEmpty() || eq_txt.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please fill in all fields.", "Warning", JOptionPane.WARNING_MESSAGE);

            }else{
                HR_Manager hr = new HR_Manager();
                hr.updateSet(name_txt , add_txt ,eq_txt , passv);
                
                Hr_Manager_service hr_service = new Hr_Manager_service();
                boolean status = hr_service.updateUser(id, hr);
                if (status) {
                    view_table();
                    fun_desable_update_delete();
                    clearfun();
                   

                    JOptionPane.showMessageDialog(null, "HR Manager updated successfully", "Update Status", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "Failed to update HR Manager", "Update Status", JOptionPane.ERROR_MESSAGE);
                }
            }
        }else{
            JOptionPane.showMessageDialog(null, "Cancel updating.", "Cancel Update", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void hrtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hrtableMouseClicked
        fun_enable_update_delete();
        int rowIndex = hrtable.getSelectedRow();

        if (rowIndex != -1) {
            DefaultTableModel model = (DefaultTableModel) hrtable.getModel();

            id = (int) model.getValueAt(rowIndex, 0);
            email_for_delete = (String) model.getValueAt(rowIndex, 2);
            
            txtName.setText((String) model.getValueAt(rowIndex, 1));
            txtEmail.setText((String) model.getValueAt(rowIndex, 2));
            txtBod.setText((String) model.getValueAt(rowIndex, 3));
            txtEducationQualification.setText((String) model.getValueAt(rowIndex, 4));
            txtNIC.setText((String) model.getValueAt(rowIndex, 5));
            txtTel.setText((String) model.getValueAt(rowIndex, 6));
            txtAddress.setText((String) model.getValueAt(rowIndex, 7));
 
            txtNIC.setEnabled(false);
            txtTel.setEnabled(false);
            txtBod.setEnabled(false);
            txtEmail.setEnabled(false);
            
            Border redBorder = BorderFactory.createLineBorder(Color.RED);
            txtNIC.setBorder(redBorder);
            txtTel.setBorder(redBorder);
            txtBod.setBorder(redBorder);
            txtEmail.setBorder(redBorder);
        }
    }//GEN-LAST:event_hrtableMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        
        LocalStorage storage = new LocalStorage();
        if("Admin".equals(storage.getData("actor"))){
            this.setVisible(false);
            Admin_gui adminForm = new Admin_gui();
            adminForm.setVisible(true);
        }else if("HR Manager".equals(storage.getData("actor"))){
            this.setVisible(false);
            HR_Manager_dashboard hrManagerDash = new HR_Manager_dashboard();
            hrManagerDash.setVisible(true);
        }       
    }//GEN-LAST:event_jLabel3MouseClicked

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearfun();
        fun_desable_update_delete();
    }//GEN-LAST:event_btnClearActionPerformed

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        int dialogResult = JOptionPane.showConfirmDialog(null, "Are you sure you want to logout?", "Logout Confirmation", JOptionPane.YES_NO_OPTION);
        if (dialogResult == JOptionPane.YES_OPTION) {
            this.setVisible(false);
            Login form = new Login();
            form.setVisible(true);
        }
    }//GEN-LAST:event_jPanel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HR_Manager_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HR_Manager_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HR_Manager_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HR_Manager_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HR_Manager_gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JTable hrtable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtBod;
    private javax.swing.JTextField txtEducationQualification;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNIC;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables

    private void fun_desable_update_delete() {
        btnDelete.setEnabled(false);
        btnUpdate.setEnabled(false);
        btnSave.setEnabled(true); 
        
        txtNIC.setEnabled(true);
        txtTel.setEnabled(true);
        txtBod.setEnabled(true);
        txtEmail.setEnabled(true);

        Border redBorder = BorderFactory.createLineBorder(Color.black);
        txtNIC.setBorder(redBorder);
        txtTel.setBorder(redBorder);
        txtBod.setBorder(redBorder);
        txtEmail.setBorder(redBorder); 
    }
    private void fun_enable_update_delete() {
        btnDelete.setEnabled(true);
        btnUpdate.setEnabled(true);
        btnSave.setEnabled(false);
    }

    private void clearfun() {
        txtName.setText("");
        txtAddress.setText("");
        txtNIC.setText("");
        txtBod.setText("");
        txtEducationQualification.setText("");
        txtEmail.setText("");
        txtTel.setText("");
    }

    private void view_table() {
        Hr_Manager_service hr_service = new Hr_Manager_service();
        List<HR_Manager> hrmanager = hr_service.retrieveAllHRMANAGER();
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Id");
        model.addColumn("Name");
        model.addColumn("Email");
        model.addColumn("BOD");
        model.addColumn("Education Qualification");
        model.addColumn("NIC");
        model.addColumn("Telephone Number");
        model.addColumn("Address");
        model.addColumn("Joined Date");


        for (HR_Manager hrman : hrmanager) {
            model.addRow(new Object[]{
                hrman.getId(),
                hrman.getName(),
                hrman.getEmail(),
                hrman.getBod(), 
                hrman.getEducation_qualification(),
                hrman.getNic(),
                hrman.getTelephoneNumber(),
                hrman.getAddress(),
                hrman.getTimestamp()
            });
        }

        hrtable.setModel(model);
    }

}
