/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assingment;

import javax.swing.JOptionPane;

/**
 *
 * @author MSI
 */
public class Loading extends javax.swing.JFrame {

    /**
     * Creates new form Loading
     */
    public Loading() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Pbar = new javax.swing.JProgressBar();
        txt = new javax.swing.JLabel();
        pnumber = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(64, 5, 64));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Studies");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Colombo institute of");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, -1, -1));
        jPanel1.add(Pbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 810, 10));

        txt.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txt.setForeground(new java.awt.Color(255, 255, 255));
        txt.setText("Loading ............");
        jPanel1.add(txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 250, -1));

        pnumber.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        pnumber.setForeground(new java.awt.Color(255, 255, 255));
        pnumber.setText("0 %");
        jPanel1.add(pnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 440, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assingment/Teacher-rafiki (2).png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, 290));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 490));

        setSize(new java.awt.Dimension(808, 488));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    Loading nm = new Loading();
        nm.setVisible(true);
        try{
            for(int i=1; i<=100; i++){
                Thread.sleep(50);
              nm.pnumber.setText(i+"%");
               
                if(i==10){
                    nm.txt.setText("Turning on System.......");
                    
                }
                if(i==30){
                    nm.txt.setText("Loading Items.......");  
            }
                if(i==50){
                    nm.txt.setText("Connecting Database.......");  
            }
                if(i==70){
                    nm.txt.setText("Check databases.......");  
            }
                if(i==90){
                    nm.txt.setText("Loading successful.......");  
            }
            nm.Pbar.setValue(i);
            
        }
            
            
        }catch (Exception e)
                {
                  JOptionPane.showMessageDialog(null,e);
                }
        
         nm.setVisible(false);
         Login s=new Login();
         s.setVisible(true);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loading().setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar Pbar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel pnumber;
    private javax.swing.JLabel txt;
    // End of variables declaration//GEN-END:variables
}
